// import { NextPage } from "next";
// import Head from "next/head";
// import Link from "next/link";
// // import LandingPageTemplate from "@/templates/LandingPage/LandingPageTemplate";

// const Index: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>reexar</title>
//         <meta name="description" content="Generated by Create Next Stack." />
//       </Head>
//       {/* <nav>
//         <div className="navbar bg-neutral text-neutral-content">
//           <a className="btn btn-ghost normal-case text-xl ">ReexarAI</a>
//         </div>
//       </nav> */}
//       {/* <LandingPageTemplate /> */}

//       <div className="container mx-auto">
//           Ringkasan
//         </div>
//         <form action="#" className="">

//         </form>

//     </>
//   );
// };

// export default Index;

import React from "react";
import SummarizeComponent from "../components/SummaryComponent";

const HomePage: React.FC = () => {
  return (

    <div className="py-10 px-10">
      <div className="py-5 px-2">

        <h1 className="font-bold text-4xl items-center text-success">
          Summarizer
        </h1>

        <p className="text-lg text-gray-500">
          Summarizer is a tool for summarizing text.
        </p>
        
      </div>

        <SummarizeComponent />

      <footer>
        <div className="py-5 px-2">
          <p className="text-sm font-medium text-gray-500 text-right">© 2023 ReexarAI</p>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
