// import { NextPage } from "next";
// import Head from "next/head";
// import Link from "next/link";
// // import LandingPageTemplate from "@/templates/LandingPage/LandingPageTemplate";

// const Index: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>reexar</title>
//         <meta name="description" content="Generated by Create Next Stack." />
//       </Head>
//       {/* <nav>
//         <div className="navbar bg-neutral text-neutral-content">
//           <a className="btn btn-ghost normal-case text-xl ">ReexarAI</a>
//         </div>
//       </nav> */}
//       {/* <LandingPageTemplate /> */}

//       <div className="container mx-auto">
//           Ringkasan
//         </div>
//         <form action="#" className="">

//         </form>

//     </>
//   );
// };

// export default Index;


import React from 'react';
import SummarizeComponent from '../components/SummaryComponent';

const HomePage: React.FC = () => {
  return (
    <div>
      <h1>Website Meringkas Paragraf</h1>
      <SummarizeComponent />
    </div>
  );
};

export default HomePage;

