import { NextPage } from "next";
import Head from "next/head";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>reexar</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <nav>
        <div className="navbar bg-neutral text-neutral-content">
          <a className="btn btn-ghost normal-case text-xl ">ReexarAI</a>
        </div>
      </nav>

    </>
  );
};

export default Index;
